# Generated by Django 4.2.15 on 2024-08-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0002_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('image', models.ImageField(blank=True, default='course_pics/default.jpg', upload_to='course_pics')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.profile')),
            ],
        ),
    ]
