# Generated by Django 4.2.15 on 2024-08-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0004_coursematerial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
