# Generated by Django 4.2.15 on 2024-08-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0008_enroll_alter_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
