# Generated by Django 4.2.15 on 2024-09-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0010_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.profile')),
            ],
        ),
    ]
