# Generated by Django 4.2.15 on 2024-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0011_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
