# Generated by Django 4.2.15 on 2024-09-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0012_enroll_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.profile')),
            ],
        ),
    ]
